### ISSUE TITLE
renameNumberSuffixedComponents definition?

### ISSUE THREAD

**Issue by MugaChi** [ColmBhandal/VbaSync#3]
Hi

Do you know where is the definition of "renameNumberSuffixedComponents" ?
It's call at the end of ImportModules

**Comment by ColmBhandal** [comment]
Hi,

I can't believe that's still there... You definitely on the head of the
main branch? It's an old piece of code that's no longer used. Once upon a
time I had the Sync module coded so that it could import export itself.. It
was highly complicated for little benefit. Try delete that function call
and open a PR for me if you get it working

Colm

**Comment by ColmBhandal** [comment]
Yeah I just checked main branch... That code should not be there. Delete
that line and open a PR when you get it working
